import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

import { Observable, of, Subject } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';


import { SessionService } from '@app/auth/session.service';
import { NotificationService } from '@common/notification.service';

import { LinOTPResponse } from './api';
import { SelfserviceToken, tokenDisplayData, TokenDisplayData, TokenType, unknownTokenTypeDetail } from './token';


@Injectable({
  providedIn: 'root'
})
export class TokenService {

  private userserviceBase = `/userservice/`;
  private userserviceEndpoints = {
    tokens: 'usertokenlist',
    serialByOTP: 'getSerialByOtp',
  };

  /**
   * Fires whenever the token changes resulting in a token list reload.
   *
   * Optionally emits the serial of the updated token.
   * If a serial is provided, the consumer can use it to focus the
   * corresponding element after the list has been refreshed.
   */
  private emitTokenUpdateeSource = new Subject<string | undefined>();
  tokenUpdateEmitted$ = this.emitTokenUpdateeSource.asObservable();

  constructor(
    private http: HttpClient,
    private sessionService: SessionService,
    private notificationService: NotificationService,
  ) { }

  updateTokenList(serial?: string) {
    this.emitTokenUpdateeSource.next(serial);
  }

  getSelfserviceTokens(): Observable<SelfserviceToken[]> {
    return this.getTokens().pipe(
      map(res => {
        return res.result.value.map(t => new SelfserviceToken(t));
      }),
      catchError(this.handleError('getting tokens failed', []))
    );
  }

  getTokens() {
    const url = this.userserviceBase + this.userserviceEndpoints.tokens;
    return this.http.get<LinOTPResponse<any[]>>(url, { params: { session: this.sessionService.getSession() } })
  }

  getToken(serial: string): Observable<SelfserviceToken> {
    return this.getSelfserviceTokens().pipe(
      map(tokens => tokens.find(t => t.serial === serial)),
    );
  }

  getTypeDetails(type: TokenType | 'assign'): TokenDisplayData {
    return tokenDisplayData.find(td => td.type === type.toLowerCase()) || unknownTokenTypeDetail;
  }

  getEnrollableTypes(): TokenDisplayData[] {
    return tokenDisplayData.filter(t => t.enrollmentPermission);
  }

  /**
   * Request a token's serial from the backend given an OTP generated by that token.
   *
   * @param {string} otp the otp generated by the token
   * @returns {Observable<string>} an observable of the token serial
   * @memberof TokenService
   */
  getSerialByOTP(otp: string): Observable<string> {
    const url = this.userserviceBase + this.userserviceEndpoints.serialByOTP;
    const params = {
      session: this.sessionService.getSession(),
      otp,
    };
    return this.http.get<LinOTPResponse<{ serial: string; }>>(url, { params }).pipe(
      map(t => t.result.value.serial))
      .pipe(
        tap(result => {
          if (result === '') {
            this.notificationService.errorMessage($localize`Token serial not found for given OTP`);
          }
        }),
        catchError(this.handleError('retrieving token serial failed', null))
      );
  }

  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {
      this.notificationService.errorMessage($localize`Error: ${operation}. Please try again or contact an administrator`);
      return of(result as T);
    };
  }
}
