#!/bin/sh

# This script ensures that the package version is appropriate
# for the distribution that we are building for.
#
# = Snapshot builds =
# We use git-buildpackage's dch subcommand to generate a changelog
# containing git commit information. While not as good as a hand
# edited changelog, it contains enough information to help testers
# understand which changes are contained in the package.
#
# We use gbp-dch to set a version number based on the commit date
# and git commit id.
#
# = Building from tags =
# If we are building for a tag, we generate final release packages:
#   * Leave the changelog entries as they are
#   * If a backport, generate a backport changelog entry
#
# = Distribution flag =
# In all cases, we want to make sure that the distribution name
# is set. This is to ensure that reprepro assigns the package to
# the correct distribution. We determine the distribution
# using lsb_release.


# Determine the release name and number that we are building for
DEBIAN_RELEASE_NAME="$(lsb_release -c -s)"

# Ensure generated changelog entries have the same
export DEBEMAIL="$(dpkg-parsechangelog -S Maintainer)"

# To ensure package version numbers for backports follow in the
# correct order, we treat stable / oldstable as a
# backport build
if [ "$DEBIAN_RELEASE_NAME" = buster ]; then
  BPO_FLAG=
else
  BPO_FLAG=--bpo
fi

# Are we building a snapshot or tag?
if [ ! -n "${CI_COMMIT_TAG}" ]; then
  # Snapshot build

  # install git-buildpackage
  which gbp || apt-get install -y --no-install-recommends git-buildpackage

  COMMIT_TS=$(git show -s --pretty=format:%ct HEAD)
  COMMIT_DATE=$(date --date="@${COMMIT_TS}" +%Y%m%d%H%M)
  CURRENT_VERSION="$(dpkg-parsechangelog -S Version)"

  gbp dch --auto --snapshot --snapshot-number="${COMMIT_DATE}" --no-multimaint --ignore-branch $BPO_FLAG
else
  # Tagged build

  # Only create a changelog entry if we are creating a backport version
  if [ -n "$BPO_FLAG" ]; then
    dch --bpo "Autobuilt by CI"
  fi
fi

# In order to upload to our internal archive, we need to set the distribution to
# correct destination distribution
CURRENT_DISTRIBUTION="$(dpkg-parsechangelog -S Distribution)"
sed "1s/ ${CURRENT_DISTRIBUTION}\(; urgency=\)/ ${DEBIAN_RELEASE_NAME}\1/" -i debian/changelog

# Show the results
dpkg-parsechangelog
